brainfuck: fix compiler warnings with gcc 4.6.3
With gcc 4.6.3 and the default compiler flags from the Makefile,
the following errors were produced which prevented compilation:

brainfuck.c:73:3: error: format not a string literal and no format
arguments [-Werror=format-security]
brainfuck.c:78:3: error: format not a string literal and no format
arguments [-Werror=format-security]
brainfuck.c:249:8: error: ignoring return value of 'fread', declared
with attribute warn_unused_result [-Werror=unused-result]

This patch corrects the errors and does a small fix to ensure that
fclose() is called even if the file length is 0.